#!/bin/bash

# install.sh -- installer for grubiso
# Copyright (C) 2012 Alex Scheel
# Licensed under the terms of the GNU GPL v3.


# Check for root
if [ $(id -u) == 0 ]; then
    wait
else
    echo "Error: Must be root to run this script" 1>&2
    exit 1
fi

# Read isos directory.
dir=$(grep 'iso' /etc/grubiso.conf | sed 's/^iso: //g')
tmp='/tmp/mnt'

# Check for temporary mount directry.
if [ -e $tmp ]; then
	umount $tmp 2>&1 >/dev/null
else
    mkdir $tmp 2>&1 >/dev/null
fi

# Find livecd images.
for file in `find $dir/*.iso`; do
	name=$(basename $file)
	linux=""
	initrd=""

    
	echo -e "Found $name" 1>&2
    
    # Tested distributions/versions:
    # Archlinux 2011.08.19
    # Fedora 17
    # debian live lxde 6.0.4
    # linuxmint cinnamon 13
    # ubuntu 10.10

    
    
	a=$(mount -o loop $file $tmp 2>&1 1>/dev/null)
	pushd $tmp 2>&1 >/dev/null
	
	initfile=""
	linuxfile=""
	
	test=''
	if [ -d "$tmp/live" ]; then
	    test='live'
    elif [ -d "$tmp/casper" -a -d "$tmp/install" ]; then
        test='casper install'
    elif [ -d "$tmp/isolinux" ]; then
        test='isolinux'
    fi
	
	for zfile in $(find $test); do
		if [ "$(file $zfile | grep -io 'Linux kernel')" == "Linux kernel" ]; then
			linuxfile="$zfile"
		elif [ "$(echo $zfile | grep -io 'initrd')" == "initrd" ]; then
			initfile="$zfile"
		fi
	done
	
	if [ "$linuxfile" != '' -a "$initfile" != '' ]; then
	    linux="linux (loop)/$linuxfile boot=casper iso-scan/filename=$file noeject noprompt --"
	    initrd="initrd (loop)/$initfile"
    else
        wait
    fi
    
    popd 2>&1 >/dev/null
	a=$(umount $tmp 2>&1 >/dev/null)


	if [ "$linux" != "" -a "$initrd" != "" ]; then
		echo -e "menuentry \"$name\" {"
		echo -e "\tloopback loop $file"
		if [ "$linux" != "" ]; then
			echo -e "\t$linux"
		fi

		if [ "$initrd" != "" ]; then
			echo -e "\t$initrd"
		fi

		echo -e "}"
	fi

done

a=$(umount $tmp 2>&1 >/dev/null)
rm $tmp -r 2>&1 >/dev/null
